// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3VJRX2nwOGz39QFiXTgAyOjPP1ZMR1LY',
    appId: '1:652597646828:web:192e82ace00b421279dcc9',
    messagingSenderId: '652597646828',
    projectId: 'nagarik-action',
    authDomain: 'nagarik-action.firebaseapp.com',
    storageBucket: 'nagarik-action.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMszGiQZajgpT5VZfjR189UnuF7cTh6cY',
    appId: '1:652597646828:android:8cbe2894da6bf23b79dcc9',
    messagingSenderId: '652597646828',
    projectId: 'nagarik-action',
    storageBucket: 'nagarik-action.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeTJDdAP3SGI0srJEUlJJbrypuR2X31pU',
    appId: '1:652597646828:ios:399aaa36cabc89db79dcc9',
    messagingSenderId: '652597646828',
    projectId: 'nagarik-action',
    storageBucket: 'nagarik-action.firebasestorage.app',
    iosBundleId: 'com.example.nagarikAction4thsemproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeTJDdAP3SGI0srJEUlJJbrypuR2X31pU',
    appId: '1:652597646828:ios:399aaa36cabc89db79dcc9',
    messagingSenderId: '652597646828',
    projectId: 'nagarik-action',
    storageBucket: 'nagarik-action.firebasestorage.app',
    iosBundleId: 'com.example.nagarikAction4thsemproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3VJRX2nwOGz39QFiXTgAyOjPP1ZMR1LY',
    appId: '1:652597646828:web:c80d92a48e6bdaa179dcc9',
    messagingSenderId: '652597646828',
    projectId: 'nagarik-action',
    authDomain: 'nagarik-action.firebaseapp.com',
    storageBucket: 'nagarik-action.firebasestorage.app',
  );
}
